# Generated by Django 5.1.3 on 2025-06-28 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, choices=[('cover', 'Cover'), ('thumbnail', 'Thumbnail')], max_length=50)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform_id', models.CharField(max_length=255, unique=True)),
                ('platform_url', models.URLField(blank=True, max_length=255)),
                ('founded', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('global', 'Global'), ('continental', 'Continental'), ('multi-national', 'Multi-National'), ('national', 'National'), ('hype', 'Hype'), ('upcoming', 'Upcoming'), ('underground', 'Underground'), ('monitoring', 'Monitoring'), ('inactive', 'Inactive')], default='national', max_length=50)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_artists', to='main.label')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_tracks', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('popularity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('genres', models.ManyToManyField(blank=True, related_name='albums', to='main.genre')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_albums', to='main.artist')),
                ('main_artists', models.ManyToManyField(related_name='main_albums', to='main.artist')),
                ('images', models.ManyToManyField(related_name='albums', to='main.image')),
                ('labels', models.ManyToManyField(blank=True, related_name='albums', to='main.label')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('popularity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='main.album')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_tracks', to='main.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='tracks', to='main.genre')),
                ('images', models.ManyToManyField(related_name='tracks', to='main.image')),
                ('labels', models.ManyToManyField(blank=True, related_name='tracks', to='main.label')),
                ('main_artists', models.ManyToManyField(related_name='main_tracks', to='main.artist')),
            ],
        ),
    ]
