# Generated by Django 5.1.3 on 2025-06-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image_label_artist_album_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='main.image'),
        ),
    ]
