# Generated by Django 5.1.3 on 2025-06-29 21:24

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_artist_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
