# Generated by Django 5.1.3 on 2025-06-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_label_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
