# Generated by Django 5.1.3 on 2025-06-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='main.genre'),
        ),
    ]
