# Generated by Django 5.1.3 on 2025-06-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_artist_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='platform_url',
        ),
    ]
